import sys

FILE = "frontend/app/dashboard/timetable/page.tsx"

with open(FILE, "r", encoding="utf-8") as f:
    content = f.read()

# Normalize to LF
content = content.replace("\r\n", "\n")

# ---- OLD BLOCK (exact match after LF normalization) -------------------------
OLD = (
    "            {/* Header & Controls */}\n"
    "            <div className=\"flex flex-col md:flex-row justify-between items-start md:items-center gap-4 shrink-0 print:hidden\">\n"
    "                <div>\n"
    "                    <div className=\"flex items-center gap-2\">\n"
    "                        <h1 className=\"text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-50\">Master Timetable</h1>\n"
    "                        {slots.length > 0 && (\n"
    "                            <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${\n"
    "                                visibleSlots.length === slots.length\n"
    "                                    ? 'bg-slate-100 dark:bg-slate-800 text-slate-500'\n"
    "                                    : 'bg-violet-100 dark:bg-violet-500/20 text-violet-700 dark:text-violet-300'\n"
    "                            }`}>\n"
    "                                {visibleSlots.length === slots.length\n"
    "                                    ? `${slots.length} slots`\n"
    "                                    : `${visibleSlots.length} / ${slots.length} slots`}\n"
    "                            </span>\n"
    "                        )}\n"
    "                    </div>\n"
    "                    <p className=\"text-sm text-slate-500 dark:text-slate-400\">\n"
    "                        {activeFilter === \"All Divisions\"\n"
    "                            ? \"Viewing all divisions. Use the filter to isolate a single division's schedule.\"\n"
    "                            : `Filtered to: ${activeFilter} \u2014 each slot shows exactly one class.`}\n"
    "                    </p>\n"
    "                </div>\n"
    "                <div className=\"flex items-center gap-2 flex-wrap\">\n"
    "                    {/* Search box */}\n"
    "                    <div className=\"relative\">\n"
    "                        <Search className=\"absolute left-2.5 top-2.5 h-3.5 w-3.5 text-slate-400\" />\n"
    "                        <Input\n"
    "                            placeholder=\"Search subject or faculty...\"\n"
    "                            value={searchQuery}\n"
    "                            onChange={(e) => setSearchQuery(e.target.value)}\n"
    "                            className=\"pl-8 h-9 w-48 text-sm\"\n"
    "                        />\n"
    "                        {searchQuery && (\n"
    "                            <button onClick={() => setSearchQuery(\"\")} className=\"absolute right-2 top-2.5 text-slate-400 hover:text-slate-600\">\n"
    "                                <X className=\"w-3.5 h-3.5\" />\n"
    "                            </button>\n"
    "                        )}\n"
    "                    </div>\n"
    "\n"
    "                    {/* Division filter */}\n"
    "                    <div className=\"relative\">\n"
    "                        <Filter className=\"absolute left-2.5 top-2.5 h-4 w-4 text-slate-400\" />\n"
    "                        <select\n"
    "                            className=\"pl-9 pr-4 py-2 bg-slate-100 dark:bg-slate-900 border-none rounded-md text-sm font-medium focus:ring-2 focus:ring-blue-500 appearance-none h-9\"\n"
    "                            value={activeFilter}\n"
    "                            onChange={(e) => setActiveFilter(e.target.value)}\n"
    "                        >\n"
    "                            {availableFilters.map(f => (\n"
    "                                <option key={f} value={f}>{f}</option>\n"
    "                            ))}\n"
    "                        </select>\n"
    "                    </div>\n"
    "\n"
    "                    {/* Faculty filter */}\n"
    "                    <div className=\"relative\">\n"
    "                        <Users className=\"absolute left-2.5 top-2.5 h-4 w-4 text-slate-400\" />\n"
    "                        <select\n"
    "                            className=\"pl-9 pr-4 py-2 bg-slate-100 dark:bg-slate-900 border-none rounded-md text-sm font-medium focus:ring-2 focus:ring-blue-500 appearance-none h-9\"\n"
    "                            value={facultyFilter}\n"
    "                            onChange={(e) => setFacultyFilter(e.target.value)}\n"
    "                        >\n"
    "                            {availableFaculty.map(f => (\n"
    "                                <option key={f} value={f}>{f}</option>\n"
    "                            ))}\n"
    "                        </select>\n"
    "                    </div>\n"
    "\n"
    "                    <DropdownMenu>\n"
    "                        <DropdownMenuTrigger asChild>\n"
    "                            <Button variant=\"outline\" size=\"sm\" className=\"h-9\">\n"
    "                                <Download className=\"w-4 h-4 mr-2\" />\n"
    "                                Export\n"
    "                                <ChevronDown className=\"w-4 h-4 ml-2 opacity-50\" />\n"
    "                            </Button>\n"
    "                        </DropdownMenuTrigger>\n"
    "                        <DropdownMenuContent align=\"end\" className=\"w-52\">\n"
    "                            <DropdownMenuLabel className=\"text-xs\">Spreadsheet</DropdownMenuLabel>\n"
    "                            <DropdownMenuItem onClick={exportToExcel} className=\"cursor-pointer text-green-700 dark:text-green-400 focus:text-green-700 focus:bg-green-50 dark:focus:bg-green-950/50\">\n"
    "                                <FileSpreadsheet className=\"w-4 h-4 mr-2\" />\n"
    "                                Download as Excel (.xlsx)\n"
    "                            </DropdownMenuItem>\n"
    "                            <DropdownMenuSeparator />\n"
    "                            <DropdownMenuLabel className=\"text-xs\">Calendar Integration</DropdownMenuLabel>\n"
    "                            <DropdownMenuItem onClick={exportToICS} className=\"cursor-pointer text-teal-600 focus:text-teal-600 focus:bg-teal-50 dark:focus:bg-teal-950/50\">\n"
    "                                <CalendarIcon className=\"w-4 h-4 mr-2\" />\n"
    "                                Export to iCal (.ics)\n"
    "                            </DropdownMenuItem>\n"
    "                            <DropdownMenuItem onClick={pushToGoogleCalendar} className=\"cursor-pointer text-purple-600 focus:text-purple-600 focus:bg-purple-50 dark:focus:bg-purple-950/50\">\n"
    "                                <Send className=\"w-4 h-4 mr-2\" />\n"
    "                                Push to Google Calendar\n"
    "                            </DropdownMenuItem>\n"
    "                            <DropdownMenuSeparator />\n"
    "                            <DropdownMenuLabel className=\"text-xs\">Printable</DropdownMenuLabel>\n"
    "                            <DropdownMenuItem onClick={exportToPDF} className=\"cursor-pointer text-orange-600 focus:text-orange-600 focus:bg-orange-50 dark:focus:bg-orange-950/50\">\n"
    "                                <Printer className=\"w-4 h-4 mr-2\" />\n"
    "                                Save as PDF / Print\n"
    "                            </DropdownMenuItem>\n"
    "                        </DropdownMenuContent>\n"
    "                    </DropdownMenu>\n"
    "\n"
    "                    {!hideFullscreen && (\n"
    "                        <Button size=\"sm\" className=\"h-9 bg-blue-600 hover:bg-blue-700 text-white shadow-md shadow-blue-500/20 md:flex hidden\" onClick={toggleFullscreen}>\n"
    "                            {isFullscreen ? <Minimize2 className=\"w-4 h-4 mr-2\" /> : <Maximize2 className=\"w-4 h-4 mr-2\" />}\n"
    "                            {isFullscreen ? \"Exit Fullscreen\" : \"Fullscreen\"}\n"
    "                        </Button>\n"
    "                    )}\n"
    "                </div>\n"
    "            </div>"
)

# ---- NEW BLOCK --------------------------------------------------------------
NEW = (
    "            {/* Header - Row 1: Title+chip | Search (full-width) | Export | Fullscreen */}\n"
    "            <div className=\"shrink-0 print:hidden space-y-2\">\n"
    "                <div className=\"flex items-center gap-3\">\n"
    "                    <div className=\"flex items-center gap-2 shrink-0\">\n"
    "                        <h1 className=\"text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-50\">Master Timetable</h1>\n"
    "                        {slots.length > 0 && (\n"
    "                            <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${visibleSlots.length === slots.length ? 'bg-slate-100 dark:bg-slate-800 text-slate-500' : 'bg-violet-100 dark:bg-violet-500/20 text-violet-700 dark:text-violet-300'}`}>\n"
    "                                {visibleSlots.length === slots.length ? `${slots.length} slots` : `${visibleSlots.length} / ${slots.length} slots`}\n"
    "                            </span>\n"
    "                        )}\n"
    "                    </div>\n"
    "                    {/* Search stretches full width */}\n"
    "                    <div className=\"relative flex-1\">\n"
    "                        <Search className=\"absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none\" />\n"
    "                        <Input\n"
    "                            placeholder=\"Search subject, faculty or room...\"\n"
    "                            value={searchQuery}\n"
    "                            onChange={(e) => setSearchQuery(e.target.value)}\n"
    "                            className=\"pl-9 h-9 w-full text-sm\"\n"
    "                        />\n"
    "                        {searchQuery && (\n"
    "                            <button onClick={() => setSearchQuery(\"\")} className=\"absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600\">\n"
    "                                <X className=\"w-3.5 h-3.5\" />\n"
    "                            </button>\n"
    "                        )}\n"
    "                    </div>\n"
    "                    {/* Export */}\n"
    "                    <DropdownMenu>\n"
    "                        <DropdownMenuTrigger asChild>\n"
    "                            <Button variant=\"outline\" size=\"sm\" className=\"h-9 shrink-0\">\n"
    "                                <Download className=\"w-4 h-4 mr-2\" />Export<ChevronDown className=\"w-4 h-4 ml-2 opacity-50\" />\n"
    "                            </Button>\n"
    "                        </DropdownMenuTrigger>\n"
    "                        <DropdownMenuContent align=\"end\" className=\"w-52\">\n"
    "                            <DropdownMenuLabel className=\"text-xs\">Spreadsheet</DropdownMenuLabel>\n"
    "                            <DropdownMenuItem onClick={exportToExcel} className=\"cursor-pointer text-green-700 dark:text-green-400 focus:text-green-700 focus:bg-green-50 dark:focus:bg-green-950/50\">\n"
    "                                <FileSpreadsheet className=\"w-4 h-4 mr-2\" />Download as Excel (.xlsx)\n"
    "                            </DropdownMenuItem>\n"
    "                            <DropdownMenuSeparator />\n"
    "                            <DropdownMenuLabel className=\"text-xs\">Calendar Integration</DropdownMenuLabel>\n"
    "                            <DropdownMenuItem onClick={exportToICS} className=\"cursor-pointer text-teal-600 focus:text-teal-600 focus:bg-teal-50 dark:focus:bg-teal-950/50\">\n"
    "                                <CalendarIcon className=\"w-4 h-4 mr-2\" />Export to iCal (.ics)\n"
    "                            </DropdownMenuItem>\n"
    "                            <DropdownMenuItem onClick={pushToGoogleCalendar} className=\"cursor-pointer text-purple-600 focus:text-purple-600 focus:bg-purple-50 dark:focus:bg-purple-950/50\">\n"
    "                                <Send className=\"w-4 h-4 mr-2\" />Push to Google Calendar\n"
    "                            </DropdownMenuItem>\n"
    "                            <DropdownMenuSeparator />\n"
    "                            <DropdownMenuLabel className=\"text-xs\">Printable</DropdownMenuLabel>\n"
    "                            <DropdownMenuItem onClick={exportToPDF} className=\"cursor-pointer text-orange-600 focus:text-orange-600 focus:bg-orange-50 dark:focus:bg-orange-950/50\">\n"
    "                                <Printer className=\"w-4 h-4 mr-2\" />Save as PDF / Print\n"
    "                            </DropdownMenuItem>\n"
    "                        </DropdownMenuContent>\n"
    "                    </DropdownMenu>\n"
    "                    {/* Fullscreen */}\n"
    "                    {!hideFullscreen && (\n"
    "                        <Button size=\"sm\" className=\"h-9 bg-blue-600 hover:bg-blue-700 text-white shadow-md shadow-blue-500/20 md:flex hidden shrink-0\" onClick={toggleFullscreen}>\n"
    "                            {isFullscreen ? <Minimize2 className=\"w-4 h-4 mr-2\" /> : <Maximize2 className=\"w-4 h-4 mr-2\" />}\n"
    "                            {isFullscreen ? \"Exit\" : \"Fullscreen\"}\n"
    "                        </Button>\n"
    "                    )}\n"
    "                </div>\n"
    "                {/* Row 2: Description | Division filter | Faculty filter */}\n"
    "                <div className=\"flex items-center justify-between gap-3 flex-wrap\">\n"
    "                    <p className=\"text-sm text-slate-500 dark:text-slate-400\">\n"
    "                        {activeFilter === \"All Divisions\" ? \"Viewing all divisions. Use the filter to isolate a single division's schedule.\" : `Filtered to: ${activeFilter} \u2014 each slot shows exactly one class.`}\n"
    "                    </p>\n"
    "                    <div className=\"flex items-center gap-2 shrink-0\">\n"
    "                        <div className=\"relative\">\n"
    "                            <Filter className=\"absolute left-2.5 top-2.5 h-4 w-4 text-slate-400 pointer-events-none\" />\n"
    "                            <select className=\"pl-9 pr-4 py-2 bg-slate-100 dark:bg-slate-900 border-none rounded-md text-sm font-medium focus:ring-2 focus:ring-blue-500 appearance-none h-9\" value={activeFilter} onChange={(e) => setActiveFilter(e.target.value)}>\n"
    "                                {availableFilters.map(f => <option key={f} value={f}>{f}</option>)}\n"
    "                            </select>\n"
    "                        </div>\n"
    "                        <div className=\"relative\">\n"
    "                            <Users className=\"absolute left-2.5 top-2.5 h-4 w-4 text-slate-400 pointer-events-none\" />\n"
    "                            <select className=\"pl-9 pr-4 py-2 bg-slate-100 dark:bg-slate-900 border-none rounded-md text-sm font-medium focus:ring-2 focus:ring-blue-500 appearance-none h-9\" value={facultyFilter} onChange={(e) => setFacultyFilter(e.target.value)}>\n"
    "                                {availableFaculty.map(f => <option key={f} value={f}>{f}</option>)}\n"
    "                            </select>\n"
    "                        </div>\n"
    "                    </div>\n"
    "                </div>\n"
    "            </div>"
)

if OLD in content:
    content = content.replace(OLD, NEW, 1)
    with open(FILE, "w", encoding="utf-8") as f:
        f.write(content)
    print("SUCCESS")
else:
    print("NOT FOUND - checking partial...")
    # find where it diverges
    for i in range(0, len(OLD), 50):
        if OLD[:i+50] not in content:
            print(f"Diverges around char {i}: {repr(OLD[i:i+80])}")
            break
    sys.exit(1)
