import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";

/**
 * POST /api/calendar/push
 * Reads the latest active timetable for the institution and pushes each slot
 * as a weekly-recurring Google Calendar event using the user's stored OAuth token.
 *
 * Body: { timetable_id?: string }   — optional; defaults to latest active
 */
export async function POST(req: NextRequest) {
    try {
        const supabase = await createClient();
        const { data: { session } } = await supabase.auth.getSession();

        if (!session) {
            return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
        }

        const accessToken = session.provider_token;
        if (!accessToken) {
            return NextResponse.json(
                { error: "No Google access token found. Please reconnect your Google account in Settings." },
                { status: 403 }
            );
        }

        const body = await req.json().catch(() => ({}));
        const { timetable_id } = body;

        // Fetch institution
        const { data: profile } = await supabase
            .from("profiles")
            .select("institution_id, full_name")
            .eq("id", session.user.id)
            .single();

        if (!profile?.institution_id) {
            return NextResponse.json({ error: "No institution configured" }, { status: 400 });
        }

        // Fetch timetable
        let query = supabase
            .from("generated_timetables")
            .select("matrix_data, created_at")
            .eq("institution_id", profile.institution_id)
            .eq("status", "success");

        if (timetable_id) {
            query = query.eq("id", timetable_id);
        } else {
            query = query.order("created_at", { ascending: false }).limit(1);
        }

        const { data: tt } = await query.single();
        if (!tt?.matrix_data?.schedule) {
            return NextResponse.json({ error: "No valid timetable found" }, { status: 404 });
        }

        // Map day names → RFC 5545 BYDAY values and anchor dates (week of 2024-03-04)
        const dayMap: Record<string, { byday: string; date: string }> = {
            Mon: { byday: "MO", date: "2024-03-04" },
            Tue: { byday: "TU", date: "2024-03-05" },
            Wed: { byday: "WE", date: "2024-03-06" },
            Thu: { byday: "TH", date: "2024-03-07" },
            Fri: { byday: "FR", date: "2024-03-08" },
        };

        const schedule: any[] = tt.matrix_data.schedule;
        const results = { created: 0, failed: 0, errors: [] as string[] };

        // Push each slot as a weekly recurring event
        for (const slot of schedule) {
            const dayInfo = dayMap[slot.day];
            if (!dayInfo) continue;

            const startHour = String(slot.time_slot).padStart(2, "0");
            const endHour = String(slot.time_slot + 1).padStart(2, "0");

            const event = {
                summary: `[${slot.type ?? "Class"}] ${slot.subject}`,
                location: slot.room ?? "",
                description: [
                    `Faculty: ${slot.faculty_name ?? slot.faculty_id ?? "TBD"}`,
                    `Batches: ${(slot.targets ?? []).join(", ")}`,
                    `Type: ${slot.type ?? "—"}`,
                    `Generated by ShiftSync`,
                ].join("\n"),
                start: {
                    dateTime: `${dayInfo.date}T${startHour}:00:00`,
                    timeZone: "Asia/Kolkata",
                },
                end: {
                    dateTime: `${dayInfo.date}T${endHour}:00:00`,
                    timeZone: "Asia/Kolkata",
                },
                recurrence: [`RRULE:FREQ=WEEKLY;BYDAY=${dayInfo.byday}`],
                colorId: slot.type === "Practical" ? "2" : slot.type === "Tutorial" ? "3" : "1",
            };

            const res = await fetch(
                "https://www.googleapis.com/calendar/v3/calendars/primary/events",
                {
                    method: "POST",
                    headers: {
                        Authorization: `Bearer ${accessToken}`,
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify(event),
                }
            );

            if (res.ok) {
                results.created++;
            } else {
                results.failed++;
                const errBody = await res.json().catch(() => ({}));
                results.errors.push(`${slot.subject} (${slot.day}): ${errBody?.error?.message ?? res.status}`);
            }
        }

        return NextResponse.json({
            success: true,
            message: `Pushed ${results.created} events to Google Calendar.`,
            ...results,
        });

    } catch (err: any) {
        console.error("Calendar push error:", err);
        return NextResponse.json({ error: err.message ?? "Internal server error" }, { status: 500 });
    }
}
